name-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
categories:
  - title: 'Breaking Changes'
    labels: ['breaking']
  - title: 'New Features'
    labels: ['feature', 'enhancement']
  - title: 'Bug Fixes'
    labels: ['bug']
  - title: 'Other Changes'
    labels: ['chore', 'docs', 'refactor', 'ci']
template: |
  ## Changes
  $CHANGES
