codecov:
  require_ci_to_pass: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%
ignore:
  - "testharness/**"
  - "vuln-mcp/**"
